version: "3.9"

services:
  gcb_postgres:
    image: postgres:alpine
    container_name: gcb_postgres
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    profiles: ["dev"]

  gcb_redis:
    image: redis:alpine
    container_name: gcb_redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
    volumes:
      - redis_data:/var/lib/redisql/data
    profiles: ["dev"]

  gcb_postgres_test:
    image: postgres:alpine
    container_name: gcb_postgres_test
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    profiles: ["test"]

  gcb_redis_test:
    image: redis:alpine
    container_name: gcb_redis
    ports:
      - "${REDIS_PORT}:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    profiles: ["test"]

volumes:
  postgres_data:
  redis_data:
