version: "3.9"

services:
  gcb_node_app:
    build:
      target: dev
    command: npm run dev
    expose:
      - "${PORT}"
    ports:
      - "3000:${PORT}"
    volumes:
      - /app/node_modules
      - .:/app

  gcb_postgres:
    ports:
      - "5433:5432"
